spring:
  datasource:
    url: jdbc:mysql://localhost:3306/recipedb?useSSL=false&serverTimezone=UTC
    username: root
    password: 5766669
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect